routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dhevak', function () {
    return view('dhevak');
});

Route::get('/trello', function () {
    return view('trello');
});

Route::get('/home', function () {
    return view('home');
});

Route::resource('shares', 'ShareController');
Route::resource('projecten', 'ProjectController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $fillable = [
    'projectnaam',
    'opdracht_gever',
    'status',
    'deadline',
    'omschrijving',
    'start_fase_1',
    'einde_fase_1',
    'start_fase_2',
    'einde_fase_2',
    'start_fase_3',
    'einde_fase_3',
  ];
}

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
  protected $fillable = [
    'voornaam',
    'achternaam',
    'tussenvoegsel',
    'klantnummer',
    'email',
    'bedrijfsnaam'
  ];
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projecten = Project::all();

        return view('projecten.index', compact('projecten'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projecten.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
      $request->validate([
        'projectnaam'=>'',
        'status'=>'',
        'opdracht_gever'=> '',
        'deadline'=> '',
        'omschrijving'=> '',
        'start_fase_1' => '',
        'einde_fase_1' => '',
        'start_fase_2' => '',
        'einde_fase_2' => '',
        'start_fase_3' => '',
        'einde_fase_3' => '',

      ]);

      $project = new Project($request->all());

      $project->save();

      return redirect('/projecten')->with('Hoppaah!', 'Project is toegevoegd in de database');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $project = Project::find($id);

      return view('projecten.show', compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::find($id);

        return view('projecten.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'projectnaam'=>'',
        'status'=>'',
        'opdracht_gever'=> '',
        'opdracht_gever'=> '',
        'deadline'=> '',
        'start_fase_1' => '',
        'einde_fase_1' => '',
        'start_fase_2' => '',
        'einde_fase_2' => '',
        'start_fase_3' => '',
        'einde_fase_3' => '',
        
      ]);

      $project = Project::find($id);
      $project->projectnaam = $request->get('projectnaam');
      $project->opdracht_gever = $request->get('opdracht_gever');
      $project->deadline = $request->get('deadline');
      $project->status = $request->get('status');
      $project->omschrijving = $request->get('omschrijving');
      $project->start_fase_1 = $request->get('start_fase_1');
      $project->einde_fase_1 = $request->get('einde_fase_1');
      $project->start_fase_2 = $request->get('start_fase_2');
      $project->einde_fase_2 = $request->get('einde_fase_2');
      $project->start_fase_3 = $request->get('start_fase_3');
      $project->einde_fase_3 = $request->get('einde_fase_3');
      $project->save();

      return redirect('/projecten')->with('Wham!', 'De klus is bewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);
        $project->delete();

      return redirect('/projecten')->with('Gelukt,', 'project is verwijderd');
    }
}

app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Share;

class ShareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shares = Share::all();

        return view('shares.index', compact('shares'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shares.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // dd($request);
      $request->validate([
        'voornaam'=>'',
        'tussenvoegsel'=> '',
        'achternaam' => '',
        'email' => '',
        'klantnummer' => '',
        'bedrijfsnaam' => ''

      ]);
      $share = new Share([
        'voornaam' => $request->get('voornaam'),
        'tussenvoegsel'=> $request->get('tussenvoegsel'),
        'achternaam'=> $request->get('achternaam'),
        'email'=> $request->get('email'),
        'klantnummer'=> $request->get('klantnummer'),
        'bedrijfsnaam'=> $request->get('bedrijfsnaam')
      ]);
      $share->save();
      return redirect('/shares')->with('Hoppaah!', 'Klant is toegevoegd in de database');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $share = Share::find($id);

      return view('shares.show', compact('share'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $share = Share::find($id);

        return view('shares.edit', compact('share'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'voornaam'=>'',
        'tussenvoegsel'=> '',
        'achternaam' => '',
        'email' => '',
        'klantnummer' => '',
        'bedrijfsnaam' => ''
        
      ]);

      $share = Share::find($id);
      $share->voornaam = $request->get('voornaam');
      $share->tussenvoegsel = $request->get('tussenvoegsel');
      $share->achternaam = $request->get('achternaam');
      $share->email = $request->get('email');
      $share->klantnummer = $request->get('klantnummer');
      $share->bedrijfsnaam = $request->get('bedrijfsnaam');
      $share->save();

      return redirect('/shares')->with('Wham!', 'De klant is bewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $share = Share::find($id);
        $share->delete();

      return redirect('/shares')->with('Helaas,', 'er is een klant ontsnapt');
    }
}

resources/views/inc/footer.blade.php
<footer id="footer" class="text text-center">
<p>Copyright &copy 2019 Dhèvak</p></footer>

</body>
</html>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dhevak registratie systeem</title>
    <!-- <link href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.2.1/sandstone/bootstrap.min.css') }}" rel="stylesheet" type="text/css" /> -->
</head>

<body>
    <div class="container">
        @yield('content')
    </div>
    <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>

</html>

resources/views/projecten/create.blade.php
@include('inc.header') @extends('layout')

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dhèvak CRM</title>

    <!-- Bootstrap core CSS-->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

</head>

<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top" style="background-color:#6CB52D!important">

        <a class="navbar-brand mr-1" href="/home">Dhèvak CRM</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="/home">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/projecten">
                    <i class="fas fa-plus"></i>
                    <span>Projecten</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/shares">
                    <i class="fas fa-plus"></i>
                    <span> Klanten</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-google-drive"></i>
                    <span> Google Drive</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-trello"></i>
                    <span> Trello</span></a>
            </li>
        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#" style="color:#6CB52D">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Overview</li>
                </ol>
                @section('content')
                <style>
                    .uper {
                        margin-top: 40px;
                    }
                </style>
                <div class="card uper">
                    <div class="card-header">
                        <h2>Contact toevoegen</h2>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br /> @endif
                        <form method="post" action="{{ route('projecten.store') }}">
                            <div class="form-group">
                                {{ csrf_field() }}
                                <label for="projectnaam">Projectnaam:</label>
                                <input type="text" class="form-control" name="projectnaam" />
                            </div>
                            <div class="form-group">
                                <label for="opdracht_gever">Opdrachtgever:</label>
                                <input type="text" class="form-control" name="opdracht_gever" />
                            </div>
                            <div class="form-group">
                                <label for="deadline">Deadline:</label>
                                <input type="date" class="form-control" name="deadline" />
                            </div>
                            <div class="form-group">
                                <label for="omschrijving">Omschrijving:</label>
                                <input type="longtext" class="form-control" name="omschrijving" />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_1">Start fase 1:</label>
                                <input type="date" class="form-control" name="start_fase_1" />
                            </div>
                            <div class="form-group">
                                <label form="einde_fase_1">Einde fase 1</label>
                                <input type="date" class="form-control" name="einde_fase_1" />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_2">Start fase 2:</label>
                                <input type="date" class="form-control" name="start_fase_2" />
                            </div>
                            <div class="form-group">
                                <label form="einde_fase_2">Einde fase 2</label>
                                <input type="date" class="form-control" name="einde_fase_2" />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_3">Start fase 3:</label>
                                <input type="date" class="form-control" name="start_fase_3" />
                            </div>
                            <div class="form-group">
                                <label form="einde_fase_3">Einde fase 3</label>
                                <input type="date" class="form-control" name="einde_fase_3" />
                            </div>
                            <div class="form-group">
                                <label for="status">Status:</label>
                                <input type="text" class="form-control" name="status"  value="In onderhoud" />
                            </div>
                            <a href="projecten">
                                <button type="submit" class="btn btn-primary">Toevoegen</button>
                            </a>
                        </form>
                    </div>
                </div>
                @endsection

resources/views/projecten/edit.blade.php
@include('inc.header') @extends('layout')

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dhèvak CRM</title>

    <!-- Bootstrap core CSS-->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

</head>

<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top" style="background-color:#6CB52D!important">

        <a class="navbar-brand mr-1" href="/home">Dhèvak CRM</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="/home">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/projecten">
                    <i class="fas fa-plus"></i>
                    <span>Projecten</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/shares">
                    <i class="fas fa-plus"></i>
                    <span> Klanten</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-google-drive"></i>
                    <span> Google Drive</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-trello"></i>
                    <span> Trello</span></a>
            </li>
        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#" style="color:#6CB52D">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Overview</li>
                </ol>
                @section('content')
                <style>
                    .uper {
                        margin-top: 40px;
                    }
                </style>
                <div class="card uper">
                    <div class="card-header">
                        Contact bewerken
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br /> @endif
                        <form method="post" action="{{ route('projecten.update', $project->id) }}">
                            @method('PATCH') @csrf
                            <div class="form-group">
                                <label for="status">Status: </label>
                                <input type="text" class="form-control" name="status" value={{ $project->status }} />
                            </div>
                            <div class="form-group">
                                <label for="projectnaam">Projectnaam: </label>
                                <input type="text" class="form-control" name="projectnaam" value={{ $project->projectnaam }} />
                            </div>
                            <div class="form-group">
                                <label for="opdracht_gever">Opdracht gever:</label>
                                <input type="text" class="form-control" name="opdracht_gever" value={{ $project->opdracht_gever }} />
                            </div>
                            <div class="form-group">
                                <label for="deadline">Deadline:</label>
                                <input type="date" class="form-control" name="deadline" value={{ $project->deadline }} />
                            </div>
                            <div class="form-group">
                                <label for="deadline">Omschrijving:</label>
                                <input type="longtext" class="form-control" name="omschrijving" value={{ $project->omschrijving }} />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_1">Start fase 1:</label>
                                <input type="date" class="form-control" name="start_fase_1" value={{ $project->start_fase_1 }} />
                            </div>
                            <div class="form-group">
                                <label for="einde_fase_1">einde_fase_1</label>
                                <input type="date" class="form-control" name="einde_fase_1" value={{ $project->einde_fase_1 }} />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_2">Start fase 2:</label>
                                <input type="date" class="form-control" name="start_fase_2" value={{ $project->start_fase_2 }} />
                            </div>
                            <div class="form-group">
                                <label for="einde_fase_2">einde_fase_2</label>
                                <input type="date" class="form-control" name="einde_fase_2" value={{ $project->einde_fase_2 }} />
                            </div>
                            <div class="form-group">
                                <label for="start_fase_3">Start fase 3:</label>
                                <input type="date" class="form-control" name="start_fase_3" value={{ $project->start_fase_3 }} />
                            </div>
                            <div class="form-group">
                                <label for="einde_fase_3">einde_fase_3</label>
                                <input type="date" class="form-control" name="einde_fase_3" value={{ $project->einde_fase_3 }} />
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
                @endsection

resources/views/shares/create.blade.php
@include('inc.header') @extends('layout')

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dhèvak CRM</title>

    <!-- Bootstrap core CSS-->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

</head>

<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top" style="background-color:#6CB52D!important">

        <a class="navbar-brand mr-1" href="/home">Dhèvak CRM</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="/home">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/projecten">
                    <i class="fas fa-plus"></i>
                    <span>Projecten</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/shares">
                    <i class="fas fa-plus"></i>
                    <span> Klanten</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-google-drive"></i>
                    <span> Google Drive</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/drive/folders/0Bzj6wbyOEKM0TlBLSTFJODFzbjg" target="_blank">
                    <i class="fab fa-trello"></i>
                    <span> Trello</span></a>
            </li>
        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#" style="color:#6CB52D">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Overview</li>
                </ol>

                @section('content')
                <style>
                    .uper {
                        margin-top: 40px;
                    }
                </style>
                <div class="card uper">
                    <div class="card-header">
                        <h2>Contact toevoegen</h2>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br /> @endif
                        <form method="post" action="{{ route('shares.store') }}">
                            <div class="form-group">
                                {{ csrf_field() }}
                                <label for="voornaam">Voornaam:</label>
                                <input type="text" class="form-control" name="voornaam" />
                            </div>
                            <div class="form-group">
                                <label for="tussenvoegsel">Tussenvoegsel:</label>
                                <input type="text" class="form-control" name="tussenvoegsel" />
                            </div>
                            <div class="form-group">
                                <label for="achternaam">Achternaam:</label>
                                <input type="text" class="form-control" name="achternaam" />
                            </div>
                            <div class="form-group">
                                <label form="email">E-mail adres:</label>
                                <input type="text" class="form-control" name="email" />
                            </div>
                            <div class="form-group">
                                <label for="klantnummer"><b>Klantnummer:</b></label>
                                <input type="text" class="form-control" name="klantnummer" />
                            </div>
                            <div class="form-group">
                                <label for="bedrijfsnaam"><b>Bedrijfsnaam:</b></label>
                                <input type="text" class="form-control" name="bedrijfsnaam" />
                            </div>
                            <button type="submit" class="btn btn-primary">Toevoegen</button>
                        </form>
                    </div>
                </div>
                @endsection